### ISSUE TITLE
连接错误 

### ISSUE THREAD

**Issue by wulieee** [syuchua/QFurina-Docs#1]
哥，反向WebSocket (ws://my_qbot:8011/ws) 连接错误 Error: connect ECONNREFUSED 172.18.0.4:8011
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) 
![屏幕截图 2024-09-25 174323](https://github.com/user-attachments/assets/cb40bb7b-ef5b-4836-8503-ffdd40328120)
这是啥情况啊

**Comment by syuchua** [comment]
> 哥，反向WebSocket (ws://my_qbot:8011/ws) 连接错误 Error: connect ECONNREFUSED 172.18.0.4:8011 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) ![屏幕截图 2024-09-25 174323](https://private-user-images.githubusercontent.com/182610078/370657908-cb40bb7b-ef5b-4836-8503-ffdd40328120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjEyNTEsIm5iZiI6MTcyNzI2MDk1MSwicGF0aCI6Ii8xODI2MTAwNzgvMzcwNjU3OTA4LWNiNDBiYjdiLWVmNWItNDgzNi04NTAzLWZmZGQ0MDMyODEyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMDQyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTI4NDYxNjE1NGZjNDk1OTI4OTMxY2M5Mjk5NDlhZDQ3YjgzMzRkNTAwNzdkZjM4YzA1ZDllODc5NjE1ODI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hj03_BKzDfUSdXdCwxzJnH1kp5YgEuZXwJ-DkHnJQJI) 这是啥情况啊

消息平台配置错误，记得换机器人QQ号

**Comment by wulieee** [comment]
![image](https://github.com/user-attachments/assets/b3bbe241-ad71-40f5-b3b1-7c15d15a3a97)
哥，换了机器人qq还是报那个错t_t咋办呐大佬

**Comment by syuchua** [comment]
> ![image](https://private-user-images.githubusercontent.com/182610078/370971893-b3bbe241-ad71-40f5-b3b1-7c15d15a3a97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDE0MDEsIm5iZiI6MTcyNzM0MTEwMSwicGF0aCI6Ii8xODI2MTAwNzgvMzcwOTcxODkzLWIzYmJlMjQxLWFkNzEtNDBmNS1iM2IxLTdjMTVkMTVhM2E5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwODU4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTA2OWMxMTBmOTU4NmY1MzYyMGJhOGMyYWJmODczZTdjNTkwMWUzYTZkNzMxYWI1NTk5YjI3ZTY4NzBmMzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H8v2MA1NVe8TkjxhyWpjduJ2XRTgcBj7N_Xfh00Antk) 哥，换了机器人qq还是报那个错t_t咋办呐大佬

需要docker-compose down && docker-compose up -d 重新拉一下docker镜像，或者进napcat容器里修改配置文件
